INSERT INTO users (email, name, password, is_admin) VALUES ('test_admin@restauranto.com', 'Admin User', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', true);
INSERT INTO users (email, name, password, is_admin) VALUES ('test_user@restauranto.com', 'Client User', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);

INSERT INTO users (email, name, password, is_admin) VALUES ('john@restauranto.com', 'John', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);
INSERT INTO users (email, name, password, is_admin) VALUES ('mike@restauranto.com', 'Mike', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);
INSERT INTO users (email, name, password, is_admin) VALUES ('laura@restauranto.com', 'Laura', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);
INSERT INTO users (email, name, password, is_admin) VALUES ('monica@restauranto.com', 'Monica', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);
INSERT INTO users (email, name, password, is_admin) VALUES ('ross@restauranto.com', 'Ross', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);
INSERT INTO users (email, name, password, is_admin) VALUES ('joey@restauranto.com', 'Joey', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);
INSERT INTO users (email, name, password, is_admin) VALUES ('rachel@restauranto.com', 'Rachel', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);
INSERT INTO users (email, name, password, is_admin) VALUES ('chandler@restauranto.com', 'Chandler', '1G4VyHloHv+xoJQLRVBrw/1Oy4rJBIfbEX6xtJHuMK8=$DTHVsNpyB47eEX/kPegEE5wrVK5rKYsDkowaEKNov4zrP2GI1V6mCFq4Rixc0CJK+HkoUrsWN/p3yG+qmhuJuA==', false);

INSERT INTO restaurants (name, slug) VALUES ('Red Lobster', 'red-lobster');
INSERT INTO restaurants (name, slug) VALUES ('Banana Republic', 'banana-republic');
INSERT INTO restaurants (name, slug) VALUES ('Pizza Bazaar', 'pizza-bazaar');
INSERT INTO restaurants (name, slug) VALUES ('Delicity', 'delicity');
INSERT INTO restaurants (name, slug) VALUES ('The Sweet Goat', 'the-sweet-goat');
INSERT INTO restaurants (name, slug) VALUES ('The Sushi Drum', 'the-sushi-drum');
INSERT INTO restaurants (name, slug) VALUES ('The French Shark', 'the-french-shark');
INSERT INTO restaurants (name, slug) VALUES ('Bounty', 'bounty');
INSERT INTO restaurants (name, slug) VALUES ('The Saffron Grill', 'the-saffron-grill');
INSERT INTO restaurants (name, slug) VALUES ('The Enigma Lily', 'the-enigma-lily');
INSERT INTO restaurants (name, slug) VALUES ('The Mountain Dairy', 'the-mountain-dairy');
INSERT INTO restaurants (name, slug) VALUES ('la Poule de la Flamme', 'la-poule-de-la-flamme');
INSERT INTO restaurants (name, slug) VALUES ('Vagabonds', 'vagabonds');
INSERT INTO restaurants (name, slug) VALUES ('la Prairie', 'la-prairie');

INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,14, 6, 'Great experience. It was way too expensive The food was plentiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,9, 5, 'I loved it! It was way too expensive The whole place looked awful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,12, 5, 'Could be better. The quality was great It is really good on a budget This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,11, 5, 'It was terrible. It is really good on a budget The staff was very rude I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,13, 10, 'It was terrible. The staff was very friendly It was way too expensive This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 4, 'Could be better. The food was plentiful The whole place looked beatiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,4, 10, 'I loved it! The food was plentiful It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,13, 5, 'Could be better. It is really good on a budget The kitchen was filthy! This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,4, 10, 'Went there last night. The quality was great It was way too expensive This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,13, 10, 'Great experience. The whole place looked awful The whole place looked beatiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,6, 10, 'Went there last night. The whole place looked beatiful The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,6, 10, 'Went there last night. The whole place looked beatiful The staff was very rude I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,7, 9, 'Could be better. It is really good on a budget It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 4, 'Could be better. The kitchen was filthy! The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,11, 10, 'Great experience. The staff was very friendly The quality was great This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,5, 3, 'I loved it! The food was plentiful It was way too expensive I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,3, 5, 'Could be better. The staff was very friendly The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 8, 'Great experience. The whole place looked awful It is really good on a budget This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,9, 3, 'Went there last night. The whole place looked beatiful The whole place looked awful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,10, 3, 'I loved it! The staff was very friendly The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,4, 9, 'Went there last night. The whole place looked awful The whole place looked awful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,12, 6, 'I loved it! The food was plentiful It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,10, 3, 'I loved it! The staff was very friendly It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,10, 8, 'I loved it! The quality was great The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,14, 9, 'Could be better. The whole place looked beatiful The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,8, 5, 'Great experience. The staff was very rude The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,2, 6, 'Went there last night. The food was plentiful The whole place looked beatiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,9, 4, 'Could be better. It is really good on a budget The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,7, 4, 'Went there last night. It was way too expensive The whole place looked beatiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,8, 8, 'Great experience. The kitchen was filthy! The food was plentiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 4, 'It was terrible. The kitchen was filthy! The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,9, 4, 'Went there last night. It was way too expensive The whole place looked beatiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,10, 10, 'I loved it! The staff was very friendly The kitchen was filthy! I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,13, 4, 'I loved it! The whole place looked beatiful The food was plentiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,14, 9, 'I loved it! The quality was great It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,4, 9, 'Great experience. The whole place looked beatiful It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,14, 3, 'I loved it! The whole place looked awful The whole place looked awful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,12, 4, 'It was terrible. The food was plentiful The whole place looked beatiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,7, 6, 'I loved it! The staff was very friendly The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,6, 6, 'Went there last night. The staff was very rude The quality was great I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,9, 6, 'Great experience. The whole place looked awful The kitchen was filthy! I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,10, 4, 'Great experience. The staff was very friendly The kitchen was filthy! This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,13, 10, 'Could be better. It was way too expensive The quality was great This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,7, 10, 'It was terrible. The whole place looked beatiful The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,6, 4, 'I loved it! The whole place looked awful The staff was very friendly I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,13, 7, 'It was terrible. It is really good on a budget The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 5, 'Great experience. The staff was very friendly It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,13, 7, 'Went there last night. The kitchen was filthy! The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,8, 8, 'I loved it! The kitchen was filthy! The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,9, 8, 'Went there last night. The kitchen was filthy! The quality was great I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,7, 3, 'I loved it! It was way too expensive The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,3, 7, 'It was terrible. The staff was very friendly The whole place looked awful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,5, 4, 'Great experience. The whole place looked beatiful The quality was great I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,14, 3, 'It was terrible. It is really good on a budget It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,6, 6, 'Went there last night. The food was plentiful The kitchen was filthy! This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,7, 3, 'It was terrible. The quality was great It is really good on a budget This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,9, 6, 'Great experience. The staff was very rude The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,4, 5, 'Went there last night. The kitchen was filthy! The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,14, 5, 'Great experience. The food was plentiful The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,12, 4, 'Great experience. The staff was very rude It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,3, 7, 'I loved it! It was way too expensive It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,11, 7, 'Great experience. The whole place looked beatiful The whole place looked awful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,9, 3, 'Could be better. The whole place looked awful The food was plentiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 3, 'It was terrible. The whole place looked awful The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,5, 10, 'Great experience. It is really good on a budget The quality was great I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,11, 8, 'It was terrible. It is really good on a budget The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,12, 4, 'Went there last night. The kitchen was filthy! The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,7, 5, 'I loved it! The food was plentiful The kitchen was filthy! I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,9, 7, 'Could be better. The whole place looked beatiful It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,11, 9, 'I loved it! The staff was very rude The food was plentiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 9, 'I loved it! The whole place looked awful The whole place looked beatiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,9, 4, 'I loved it! The staff was very friendly The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 9, 'It was terrible. The whole place looked awful The food was plentiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,14, 9, 'Great experience. It was way too expensive The quality was great I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,4, 7, 'Went there last night. The whole place looked awful The whole place looked awful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,3, 3, 'It was terrible. The staff was very rude The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 3, 'Went there last night. The staff was very rude The whole place looked beatiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,7, 9, 'Could be better. The food was plentiful It was way too expensive I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,12, 5, 'Great experience. It was way too expensive The staff was very rude This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,14, 9, 'It was terrible. The food was plentiful It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,1, 5, 'Went there last night. It is really good on a budget The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,6, 7, 'Could be better. The whole place looked awful The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 10, 'Went there last night. The whole place looked awful The kitchen was filthy! This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 4, 'Great experience. It is really good on a budget It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,10, 4, 'Great experience. The kitchen was filthy! The staff was very rude I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,2, 10, 'It was terrible. The food was plentiful It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,7, 5, 'Could be better. The whole place looked beatiful The food was plentiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,3, 8, 'It was terrible. The whole place looked beatiful The kitchen was filthy! I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,1, 7, 'I loved it! The staff was very rude The staff was very friendly I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,13, 3, 'I loved it! The kitchen was filthy! It is really good on a budget I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,12, 5, 'I loved it! The kitchen was filthy! The kitchen was filthy! This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,12, 8, 'Went there last night. The whole place looked beatiful The food was plentiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 3, 'Great experience. It was way too expensive The whole place looked awful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,1, 3, 'Could be better. The staff was very friendly It is really good on a budget This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,7, 6, 'I loved it! The staff was very rude It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,3, 7, 'I loved it! The whole place looked beatiful The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,7, 9, 'Could be better. It is really good on a budget The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,6, 9, 'Great experience. The staff was very rude The food was plentiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,11, 4, 'I loved it! The kitchen was filthy! The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,4, 6, 'I loved it! The staff was very friendly It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,1, 3, 'Went there last night. The food was plentiful The quality was great I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,3, 3, 'I loved it! The staff was very rude The whole place looked beatiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,3, 4, 'Went there last night. The food was plentiful The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,13, 4, 'Great experience. The quality was great The kitchen was filthy! I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,7, 8, 'Could be better. The quality was great The kitchen was filthy! This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,12, 5, 'Great experience. The whole place looked beatiful The staff was very rude I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,1, 9, 'Could be better. The whole place looked awful The staff was very rude I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,13, 4, 'Went there last night. The food was plentiful The whole place looked awful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,12, 9, 'It was terrible. The kitchen was filthy! The kitchen was filthy! I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,9, 3, 'Great experience. The whole place looked beatiful The kitchen was filthy! I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,1, 8, 'It was terrible. The quality was great It was way too expensive This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,13, 7, 'Could be better. The staff was very rude The whole place looked beatiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 8, 'I loved it! It is really good on a budget The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,12, 9, 'It was terrible. The kitchen was filthy! The kitchen was filthy! This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,1, 10, 'It was terrible. It was way too expensive The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,7, 4, 'Went there last night. It was way too expensive The staff was very friendly I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,9, 5, 'Went there last night. The kitchen was filthy! The quality was great I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,11, 8, 'Went there last night. It is really good on a budget The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,3, 5, 'Could be better. The quality was great The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,8, 4, 'It was terrible. The food was plentiful It is really good on a budget This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 8, 'I loved it! The whole place looked awful The kitchen was filthy! This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 7, 'Went there last night. The staff was very rude The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,10, 10, 'It was terrible. It was way too expensive The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,3, 10, 'It was terrible. The whole place looked beatiful The food was plentiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,6, 10, 'Great experience. The quality was great The whole place looked beatiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,14, 8, 'Went there last night. The quality was great The whole place looked awful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,10, 7, 'Great experience. The food was plentiful The staff was very rude I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,8, 7, 'Could be better. The staff was very rude The staff was very rude This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,6, 10, 'I loved it! It is really good on a budget The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,11, 8, 'Great experience. The kitchen was filthy! The whole place looked beatiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,8, 8, 'I loved it! The staff was very rude It was way too expensive This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,3, 5, 'Could be better. The kitchen was filthy! The quality was great I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,14, 7, 'Went there last night. The staff was very friendly The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,2, 8, 'It was terrible. The staff was very friendly It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,4, 7, 'It was terrible. It is really good on a budget The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,6, 6, 'Great experience. The whole place looked awful It is really good on a budget I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,1, 7, 'Great experience. The kitchen was filthy! It is really good on a budget This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,9, 3, 'Great experience. The staff was very rude The whole place looked awful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,5, 3, 'Went there last night. The staff was very rude The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,12, 4, 'It was terrible. It was way too expensive It is really good on a budget This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,2, 9, 'Could be better. The quality was great The whole place looked awful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,2, 8, 'Great experience. The food was plentiful It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,14, 4, 'Went there last night. The whole place looked beatiful The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,9, 10, 'Went there last night. The kitchen was filthy! The kitchen was filthy! This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 5, 'It was terrible. The whole place looked awful The whole place looked awful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 3, 'Great experience. It is really good on a budget It was way too expensive I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,2, 9, 'Could be better. The staff was very friendly The whole place looked beatiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,5, 8, 'Went there last night. The whole place looked beatiful The staff was very friendly I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,13, 3, 'It was terrible. The whole place looked awful It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,3, 5, 'It was terrible. The whole place looked awful It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,13, 3, 'Great experience. The staff was very rude It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,10, 3, 'Went there last night. The quality was great The food was plentiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,13, 3, 'Could be better. The staff was very rude The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,4, 3, 'I loved it! The kitchen was filthy! The whole place looked awful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,3, 10, 'Went there last night. The whole place looked awful It is really good on a budget I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 6, 'Went there last night. The kitchen was filthy! It was way too expensive I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,5, 7, 'Went there last night. The kitchen was filthy! The staff was very rude I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,11, 7, 'It was terrible. The quality was great The food was plentiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,2, 10, 'Great experience. The kitchen was filthy! The whole place looked awful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,1, 8, 'Could be better. The staff was very friendly The quality was great This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,9, 4, 'It was terrible. The kitchen was filthy! The staff was very rude This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,9, 5, 'It was terrible. The whole place looked beatiful The whole place looked awful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,14, 8, 'Could be better. It is really good on a budget The food was plentiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,12, 7, 'I loved it! The whole place looked beatiful It is really good on a budget This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,10, 3, 'I loved it! The kitchen was filthy! The quality was great I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,14, 8, 'Could be better. The quality was great The whole place looked beatiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,7, 6, 'Great experience. The staff was very rude It is really good on a budget I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,8, 9, 'Could be better. The food was plentiful The staff was very rude I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,11, 9, 'Went there last night. The whole place looked beatiful It is really good on a budget This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,1, 7, 'Could be better. The whole place looked beatiful The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 7, 'Went there last night. The whole place looked awful It was way too expensive I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,8, 8, 'It was terrible. The whole place looked awful The whole place looked beatiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,9, 7, 'It was terrible. The whole place looked awful The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,7, 10, 'Great experience. The quality was great The staff was very rude I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,7, 3, 'It was terrible. The whole place looked awful The quality was great I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,9, 9, 'It was terrible. The staff was very friendly The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,14, 8, 'Could be better. The kitchen was filthy! The quality was great This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,6, 8, 'Could be better. The kitchen was filthy! The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,14, 4, 'It was terrible. It is really good on a budget It is really good on a budget This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,13, 10, 'Could be better. It was way too expensive The staff was very rude I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,9, 10, 'Great experience. It is really good on a budget The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,2, 6, 'Great experience. The kitchen was filthy! The food was plentiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,3, 7, 'Great experience. The staff was very friendly It was way too expensive I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 4, 'It was terrible. The kitchen was filthy! The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,4, 10, 'Went there last night. The staff was very friendly The whole place looked beatiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,3, 9, 'I loved it! The quality was great The staff was very friendly I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,10, 6, 'Went there last night. The staff was very rude The quality was great I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,6, 5, 'Could be better. The kitchen was filthy! The whole place looked beatiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,6, 6, 'It was terrible. The staff was very friendly The whole place looked beatiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,6, 4, 'Great experience. The kitchen was filthy! The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 3, 'I loved it! The food was plentiful The staff was very rude I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,11, 8, 'It was terrible. It is really good on a budget It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,9, 8, 'Could be better. The staff was very rude The kitchen was filthy! This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,4, 8, 'Great experience. The staff was very friendly The staff was very rude I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,14, 10, 'I loved it! The staff was very rude The kitchen was filthy! This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,9, 6, 'I loved it! The staff was very friendly It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,11, 3, 'Went there last night. The quality was great The whole place looked beatiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 8, 'Went there last night. The staff was very rude The whole place looked beatiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 9, 'It was terrible. The staff was very friendly The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,4, 10, 'Could be better. It is really good on a budget The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,4, 4, 'Great experience. The food was plentiful It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,13, 9, 'It was terrible. It is really good on a budget It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,2, 3, 'Went there last night. The quality was great It was way too expensive I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,2, 8, 'Could be better. The staff was very rude It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,2, 4, 'It was terrible. The kitchen was filthy! It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,6, 3, 'Great experience. The staff was very friendly It was way too expensive I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,1, 6, 'Great experience. The whole place looked beatiful It was way too expensive I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,4, 4, 'Went there last night. The kitchen was filthy! The quality was great This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 7, 'It was terrible. The whole place looked awful The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 4, 'Great experience. It is really good on a budget The quality was great I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,9, 4, 'Went there last night. The staff was very friendly It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,10, 6, 'I loved it! The staff was very friendly The staff was very rude This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 5, 'It was terrible. The quality was great The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,13, 10, 'I loved it! The whole place looked beatiful The whole place looked beatiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,14, 8, 'Went there last night. The whole place looked awful The staff was very friendly This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,3, 8, 'I loved it! The staff was very rude The staff was very rude This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,4, 9, 'I loved it! It is really good on a budget The quality was great I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,7, 8, 'Could be better. The staff was very friendly The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,13, 5, 'Great experience. The staff was very friendly The food was plentiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,2, 5, 'Could be better. The food was plentiful It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,4, 7, 'I loved it! The food was plentiful The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,7, 6, 'Great experience. The whole place looked awful The food was plentiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,11, 8, 'I loved it! It is really good on a budget The whole place looked awful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,11, 7, 'It was terrible. It is really good on a budget The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,14, 8, 'Great experience. The whole place looked beatiful The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,2, 4, 'It was terrible. It was way too expensive The quality was great This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,11, 4, 'Great experience. The food was plentiful The kitchen was filthy! I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,12, 6, 'Great experience. The staff was very rude The whole place looked awful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,12, 10, 'Could be better. It is really good on a budget The whole place looked beatiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,9, 5, 'I loved it! The staff was very friendly The whole place looked beatiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,7, 10, 'I loved it! The staff was very rude The quality was great I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,2, 7, 'Could be better. The whole place looked awful The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,11, 5, 'Could be better. The staff was very rude The food was plentiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,13, 8, 'It was terrible. The staff was very friendly The food was plentiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,14, 9, 'Great experience. The whole place looked awful The quality was great I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,5, 3, 'Great experience. The food was plentiful It was way too expensive This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,5, 9, 'Could be better. The staff was very friendly It was way too expensive I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,10, 10, 'It was terrible. The food was plentiful The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 3, 'It was terrible. The whole place looked beatiful The whole place looked awful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,6, 6, 'Could be better. The whole place looked awful The whole place looked beatiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,4, 6, 'Great experience. The quality was great The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,3, 6, 'Went there last night. The staff was very friendly The whole place looked beatiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,13, 10, 'It was terrible. The food was plentiful The staff was very rude I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,10, 6, 'Could be better. It is really good on a budget It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,2, 3, 'It was terrible. The whole place looked awful The quality was great I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,7, 6, 'Great experience. The staff was very friendly The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,1, 10, 'I loved it! It was way too expensive The quality was great I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,4, 3, 'Went there last night. It was way too expensive The whole place looked beatiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,8, 4, 'Could be better. It was way too expensive The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,6, 7, 'Went there last night. The staff was very rude The staff was very rude I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,11, 9, 'Went there last night. The staff was very rude The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,3, 9, 'Could be better. The food was plentiful The food was plentiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,9, 7, 'Great experience. The whole place looked awful The kitchen was filthy! I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,5, 5, 'It was terrible. The whole place looked beatiful The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,5, 10, 'Went there last night. The food was plentiful The staff was very friendly I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,3, 7, 'I loved it! The staff was very rude The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,8, 9, 'It was terrible. The quality was great It is really good on a budget This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,2, 4, 'I loved it! The food was plentiful The quality was great I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 7, 'Went there last night. The food was plentiful It is really good on a budget This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 9, 'It was terrible. The kitchen was filthy! The food was plentiful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,1, 5, 'Great experience. The food was plentiful The kitchen was filthy! This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,2, 3, 'Went there last night. The staff was very friendly The quality was great This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,5, 8, 'It was terrible. The staff was very rude The staff was very friendly I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,11, 8, 'Went there last night. The whole place looked beatiful The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,14, 6, 'It was terrible. It was way too expensive The kitchen was filthy! I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,13, 9, 'Great experience. The quality was great The food was plentiful This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,5, 6, 'It was terrible. The food was plentiful The food was plentiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,4, 6, 'It was terrible. The whole place looked awful The kitchen was filthy! I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,9, 8, 'Great experience. It was way too expensive The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,9, 10, 'Great experience. The staff was very rude The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,4, 3, 'Great experience. The kitchen was filthy! The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,14, 7, 'Great experience. The whole place looked beatiful The staff was very friendly I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,1, 6, 'It was terrible. The food was plentiful The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,9, 6, 'Great experience. The food was plentiful It was way too expensive This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,12, 3, 'Great experience. The kitchen was filthy! The kitchen was filthy! I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,8, 8, 'It was terrible. The quality was great It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,3, 3, 'It was terrible. The staff was very rude The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,1, 8, 'Could be better. It is really good on a budget The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,11, 7, 'Great experience. It is really good on a budget The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,10, 5, 'Went there last night. The kitchen was filthy! It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,1, 7, 'I loved it! The staff was very rude The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,14, 4, 'Could be better. The whole place looked beatiful The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,7, 6, 'Could be better. The staff was very rude It was way too expensive This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,10, 10, 'Went there last night. The whole place looked beatiful It was way too expensive I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,10, 6, 'Great experience. The quality was great The staff was very friendly This is definitely a keeper');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,12, 10, 'Could be better. The food was plentiful The staff was very friendly I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (4,13, 9, 'Great experience. The quality was great The whole place looked beatiful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,5, 7, 'Great experience. It was way too expensive It is really good on a budget I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,6, 3, 'It was terrible. The whole place looked beatiful The food was plentiful I had a lovely time');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,8, 8, 'I loved it! It was way too expensive The whole place looked awful I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,4, 6, 'Great experience. The staff was very friendly The staff was very rude This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (3,10, 7, 'Went there last night. The food was plentiful It was way too expensive I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,7, 4, 'I loved it! The whole place looked beatiful The food was plentiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,14, 9, 'Great experience. It is really good on a budget The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (5,4, 10, 'I loved it! The food was plentiful The quality was great This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,7, 4, 'Went there last night. The staff was very rude The staff was very friendly I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,5, 4, 'It was terrible. The quality was great The whole place looked beatiful This was a waste of a night');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,4, 7, 'I loved it! It was way too expensive It is really good on a budget I don''t think I''m coming back');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (2,11, 7, 'I loved it! It is really good on a budget The whole place looked awful I''d definitely go again');
INSERT INTO reviews(rating, restaurant_id, user_id, comment) VALUES (1,2, 9, 'Went there last night. The quality was great The food was plentiful I don''t think I''m coming back');
